spring.main.web-application-type=none

spring.datasource.url=jdbc:postgresql://localhost:5434/expedition_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=true