package com.beta.expedition.model.enums;

public enum NotificationType {
    CHANGE_REQUESTED, CHANGE_ACCEPTED, CHANGE_REJECTED, TERMINATION_REQUESTED, TERMINATION_ACCEPTED, TERMINATION_REJECTED, CONTRACT_PROPOSED
}
